spring.application.name=demo
server.port = 8080

# 9090 port
external-api.sse-port.base-url = http://localhost:9090
external-api.sse-port.path = /mock/stream
external-api.sse-port.scenario = client-error
external-api.sse-port.response-timeout = 15s

# 9091 port
external-api.json-port.base-url = http://localhost:9091
external-api.json-port.path = /mock/json
external-api.json-port.scenario = bad-request
# external-api.json-port.response-timeout = 5s


