spring.application.name=demo
server.port = 8080

external-api.base-url = http://localhost:9090
external-api.stream-path = /mock/stream
external-api.scenario = slow-response
external-api.response-timeout = 15s

